backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img
site_url: https://www.pasifikateachers.org

collections:
  - name: "config"
    id: "config"
    label: "Config"
    folder: "content/config"
    create: false
    slug: "{{slug}}"
    path: "index"
    editor:
      preview: false
    fields:
      - { label: "Engagements", name: "engagements", widget: "string" }
      - { label: "Registered", name: "registered", widget: "string" }
      - { label: "Participants", name: "participants", widget: "string" }
      - { label: "Launched", name: "launched", widget: "datetime" }
      - { label: "Twitter", name: "twitter", widget: "string" }
      - { label: "Facebook", name: "facebook", widget: "string" }
      - { label: "Youtube", name: "youtube", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }

  - name: "events"
    label: "Event"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    path: "{{title}}"
    editor:
      preview: false
    fields:
      - { label: "Published", name: "published", widget: "boolean", default: false }
      - { label: "Event Type", name: "type", widget: "string", required: false }
      - { label: "Event Title", name: "title", widget: "string" }
      - { label: "Event Date", name: "date", widget: "datetime" }
      - { label: "Event Duration", name: "duration", widget: "string" }
      - { label: "Registration URL", name: "registrationUrl", widget: "string" }
      - {
          label: "Registration Deadline",
          name: "registrationDeadline",
          widget: "string",
          required: false,
        }
      - { label: "Event Details", name: "body", widget: "markdown" }
